### ISSUE TITLE
is_directory in procedures raises an error when touching system or special files (Windows)

### ISSUE THREAD

**Issue by ynedelec3** [vle-forge/irritator#21] opened 2021-03-08 14:19 UTC
Hi
sort and other file dialog functions use the is_directory function which raises an error when touching pagefile.sys, hiberfil.sys...
Therefore disk C:\ cannot be a starting point for exploration in file select dialog (windows version).
I fixed it with a special sort fonction (9 cases instead of 4) but total fixing needs a modification of all the dialog functions which call is_directory.

The sort function in dialog-file.cpp becomes :

    void sort() // Nedelec
    {
        std::sort(std::begin(paths),
                  std::end(paths),
                  [](const auto& lhs, const auto& rhs) {
                      std::string slhs = lhs.filename().string();
                      std::string srhs = rhs.filename().string();
                      if (slhs.find(".sys") == -1) {
                          if (std::filesystem::is_directory(lhs)) {
                              if (srhs.find(".sys") == -1) {
                                  if (std::filesystem::is_directory(rhs))
                                      return lhs.filename() < rhs.filename();
                                  else
                                      return true;
                              } else {
                                  return true;
                              }
                          } else {
                              if (srhs.find(".sys") == -1) {
                                  if (std::filesystem::is_directory(rhs))
                                      return false;
                                  else
                                      return lhs.filename() < rhs.filename();
                              } else {
                                  return lhs.filename() < rhs.filename();
                              }
                          }
                      } else {
                          if (srhs.find(".sys") == -1) {
                              if (std::filesystem::is_directory(rhs))
                                  return false;
                              else
                                  return lhs.filename() < rhs.filename();
                          } else {
                              return lhs.filename() < rhs.filename();
                          }
                      }

        });
    }

I didn't find a solution to avoid this error, maybe a function different from is_directory, or a modified one...

**Comment by ynedelec3** [comment] 2021-03-08 15:06
sys files seem to need being left apart when building the paths vector with directory_iterator (dialo-file.cpp line 256)

**Comment by ynedelec3** [comment] 2021-03-08 15:24
This works :

   void copy_files_and_directories(const std::filesystem::path& current_path)
    {
        std::error_code err;
        for (std::filesystem::directory_iterator it(current_path, err), et;
             !err && it != et;
             ++it) {

            std::string sit = it->path().string();         // Nedelec
            if (sit.find(".sys") != -1)        // Nedelec
                continue; // Nedelec

            if (it->is_directory(err) && !err) {
                paths.emplace_back(*it);
                continue;
            }

            if (it->is_regular_file(err) && !err) {
                if (have_good_extension(*it) &&
                    have_good_file_name_starts(*it)) {
                    paths.emplace_back(*it);
                    continue;
                }
            }
        }
    }

**Comment by ynedelec3** [comment] 2021-03-09 10:26
I found another irritating file at home -)
New successful conditions are now :

if (sit.find(".sys") != -1 || sit.find("DumpStack") != -1) { // Nedelec

I can't find a generic test which could avoid calling is_directory on these special windows files

**Comment by quesnel** [comment] 2021-03-09 15:40
I cannot reproduce the problem. I think a best solution is to use `std::error_code` to avoid exception. Can you try the `test` branch ?

**Comment by ynedelec3** [comment] 2021-03-09 16:43
I've succesfully generated the Test branch but the management of error codes doesn't raise an error anymore when ouput directory is selected on C:\, dialog now shows a blank list of directories. I guess there is a real trouble with the status associated to these special files...

**Comment by quesnel** [comment] 2021-03-10 09:10
I have updated the test branch. Can you test?

FWI, I force the `git push`, you can use `git fetch origin && git reset --hard origin/test` to get the patch.

**Comment by ynedelec3** [comment] 2021-03-10 12:32
I tested but file and dir list in dialog (output directory) remains empty. File and dir list in open file dialog contains directories but it is impossible to enter in any directory listed.

**Comment by ynedelec3** [comment] 2021-03-10 12:47
It works if && ec or &&, ec1, && ec2 are suppressed after is_directory
I can see in https://developercommunity.visualstudio.com/t/stdfilesystemis-directory-fails-with-exception-if/787098 and in https://eel.is/c++draft/fs.op.is.directory#2 cited by the former link, that is_directory with ec as argument has noexcept statement whereas is_dierctory with single path doesn't have
bool filesystem::is_directory(file_status s) noexcept;
1
#
Returns: s.type() == file_­type​::​directory.
🔗
bool filesystem::is_directory(const path& p);
bool filesystem::is_directory(const path& p, error_code& ec) noexcept;

**Comment by quesnel** [comment] 2021-03-10 14:08
Ok. I think I already proposed this solution in https://github.com/vle-forge/irritator/issues/21#issuecomment-794062656

I have updated the test branch with these changes. Can you test the test branch (again...) ?

**Comment by quesnel** [comment] 2021-03-10 15:51
Cool. Thanks for the report. I merged the branches.

**Closed** 2021-03-10 15:50 UTC
